line-format: "&f- &a&l{amount} &e{item}"

hide-upgrade-description:
  - "&c✧ &fThis option allows you to hide the upgrades of the drawer."
  - "&c✧ &fUse it to keep your drawer's appearance clean and organized."

hide-key-description:
  - "&b✧ &fThis option allows you to hide the items in the drawer."
  - "&b✧ &fUse it to keep your drawer's contents private and secure."

max-upgrade-description:
  - "&d✧ &fMax Upgrade: The ultimate upgrade for your drawer."
  - "&d✧ &fIt maximizes storage capacity and optimizes your drawer's efficiency."

max-upgrade-1-multiplier: 2
max-upgrade-2-multiplier: 4
max-upgrade-3-multiplier: 6

max-amount: 100

component-name: "{name}"

components:
  hide-upgrade:
    name: "Hide Upgrade"
    lore:
      - "Crafted to conceal upgrades."
      - "Essential for covert operations."
    craft:
      shape:
        - " T "
        - "TWT"
        - " T "
      ingredients:
        W: TORCH
        T: REDSTONE
  hide-key:
    name: "Hide Key"
    lore:
      - "A key shrouded in secrecy."
      - "Use it to unlock hidden paths."
    craft:
      shape:
        - "T T"
        - "WTW"
        - "T T"
      ingredients:
        W: OBSERVER
        T: REDSTONE
  max-upgrade-1:
    name: "Max Upgrade"
    lore:
      - "Empowers your equipment to the maximum."
      - "Unleash its potential with caution."
    craft:
      shape:
        - " T "
        - "TWT"
        - " T "
      ingredients:
        W: OBSERVER
        T: REDSTONE
  max-upgrade-2:
    name: "Max Upgrade 2"
    lore:
      - "The next level of enhancement."
      - "Elevate your capabilities to new heights."
    craft:
      shape:
        - "TTT"
        - "TWT"
        - "TTT"
      ingredients:
        W: DIAMOND_BLOCK
        T: REDSTONE
  max-upgrade-3:
    name: "Max Upgrade 3"
    lore:
      - "The ultimate upgrade for the elite."
      - "Harness its power wisely."
    craft:
      shape:
        - "TTT"
        - "TWT"
        - "TTT"
      ingredients:
        W: OBSERVER
        T: IRON_BLOCK
  void-upgrade:
    name: "Void Component"
    lore:
      - "A fragment of the void's essence."
      - "Use with caution, for it hungers."
    craft:
      shape:
        - " T "
        - "TWT"
        - " T "
      ingredients:
        W: OBSERVER
        T: REDSTONE

drawer-block: CHISELED_BOOKSHELF
controller-block: OBSERVER
controller-face: EAST

drawers:
  blank:
    enabled: true
    name: "&a&lBlank"
    lore:
      - "Blank item"
      - ""
    itemParts:
      - name: blank
        type: "DISABLED"
        values: { vertical: 0, horizontal: 0, lateral: 0, scale: 0 }
    craft:
      shape:
        - "TTT"
        - "TWT"
        - "TTT"
      ingredients:
        W: GLASS
        T: REDSTONE
  advanced:
    enabled: true
    name: "&a&lAdvanced Drawer"
    lore:
      - "&a✧ &fThis drawer is an advanced drawer"
      - "&a✧ &fIt has been carefully designed to maximize storage space."
      - "&a✧ &fIt can hold a variety of items, from the smallest to the largest."
      - "&a✧ &fIt's easy to use: just right-click to open and drag-and-drop items to store them."
      - "&a✧ &fIts elegant design and advanced functionality make it a perfect choice for any home or inventory."

    textParts:
      - name: textPart0
        values: {vertical: 0, horizontal: 0.51, lateral: 0, scale: 0.25}
      - name: textPart1
        values: {vertical: 0.5, horizontal: 0.51, lateral: 0, scale: 0.25}
    itemParts:
      - name: itemPart0
        type: "ENABLED"
        values: {vertical: 0.3, horizontal: 0.51, lateral: 0, scale: 0.25}
      - name: itemPart1
        type: "ENABLED"
        values: {vertical: 0.8, horizontal: 0.51, lateral: 0, scale: 0.25}
    craft:
      shape:
        - "TTT"
        - "TWT"
        - "TTT"
      ingredients:
        W: DISPENSER
        T: SPRUCE_WOOD
  normal:
    enabled: true
    name: "&a&lNormal Drawer"
    lore:
      - "&a✧ &fThis drawer is an advanced drawer"
      - "&a✧ &fIt has been carefully designed to maximize storage space."
      - "&a✧ &fIt can hold a variety of items, from the smallest to the largest."
      - "&a✧ &fIt's easy to use: just right-click to open and drag-and-drop items to store them."
      - "&a✧ &fIts elegant design and advanced functionality make it a perfect choice for any home or inventory."

    textParts:
      - name: textPart0
        values: {vertical: 0, horizontal: 0.51, lateral: 0, scale: 0.5}
    itemParts:
      - name: itemPart0
        type: "DISABLED"
        values: {vertical: 0.5, horizontal: 0.51, lateral: 0, scale: 0.5}
    craft:
      shape:
        - "TTT"
        - "TWT"
        - "TTT"
      ingredients:
        W: DISPENSER
        T: OAK_WOOD
  controller:
    enabled: true
    name: "&a&lController"
    lore:
      - "Controller item"
      - ""
    itemParts:
      - name: controller
        values: {vertical: 0, horizontal: 0, lateral: 0, scale: 0}
    craft:
      shape:
        - "TTT"
        - "TWT"
        - "TTT"
      ingredients:
        W: TARGET
        T: REDSTONE
  superadvanced:
    enabled: true
    name: "&a&lSuper Advanced Drawer"
    lore:
      - "&a✧ &fThis drawer is an advanced drawer"
      - "&a✧ &fIt has been carefully designed to maximize storage space."
      - "&a✧ &fIt can hold a variety of items, from the smallest to the largest."
      - "&a✧ &fIt's easy to use: just right-click to open and drag-and-drop items to store them."
      - "&a✧ &fIts elegant design and advanced functionality make it a perfect choice for any home or inventory."

    textParts:
      - name: textPart0
        values: {vertical: 0, horizontal: 0.51, lateral: -0.25, scale: 0.25}
      - name: textPart1
        values: {vertical: 0.5, horizontal: 0.51, lateral: 0.25, scale: 0.25}
      - name: textPart2
        values: {vertical: 0.5, horizontal: 0.51, lateral: -0.25, scale: 0.25}
      - name: textPart3
        values: {vertical: 0, horizontal: 0.51, lateral: 0.25, scale: 0.25}
    itemParts:
      - name: itemPart0
        type: "ENABLED"
        values: {vertical: 0.3, horizontal: 0.51, lateral: -0.25, scale: 0.25}
      - name: itemPart1
        type: "ENABLED"
        values: {vertical: 0.8, horizontal: 0.51, lateral: 0.25, scale: 0.25}
      - name: itemPart2
        type: "ENABLED"
        values: {vertical: 0.8, horizontal: 0.51, lateral: -0.25, scale: 0.25}
      - name: itemPart3
        type: "ENABLED"
        values: {vertical: 0, horizontal: 0.51, lateral: 0.25, scale: 0.25}
    craft:
      shape:
        - "TTT"
        - "TWT"
        - "TTT"
      ingredients:
        W: DISPENSER
        T: JUNGLE_WOOD
  ore:
    enabled: true
    name: "&a&lOre"
    lore:
      - "Ore Drawer"
      - ""
    craft:
      shape:
        - "TTT"
        - "TWT"
        - "TTT"
      ingredients:
        W: GLASS
        T: REDSTONE